version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    command: sh -c "python backend/manage.py migrate && python backend/manage.py runserver 0.0.0.0:8080"
    env_file:
      - backend/.env
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
