# Generated by Django 4.1 on 2023-12-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="phone number"
            ),
        ),
    ]
