# Generated by Django 4.1 on 2023-12-27 22:26

import agency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizer",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=agency.models.organizer_photo_file_path
            ),
        ),
    ]
