# Generated by Django 4.1 on 2024-01-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="updated_at",
        ),
    ]
