# Generated by Django 4.1 on 2024-01-04 18:25

import agency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0002_remove_review_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=agency.models.event_type_photo_file_path,
            ),
        ),
    ]
