# Generated by Django 4.1 on 2023-12-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0003_callrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="callrequest",
            name="city",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name="callrequest",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="callrequest",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
