# Generated by Django 4.1 on 2024-01-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0006_alter_callrequest_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callrequest",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(verbose_name=200),
        ),
    ]
