# Generated by Django 4.1 on 2024-01-08 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0007_alter_callrequest_description_alter_review_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callrequest",
            name="city",
            field=models.CharField(
                blank=True,
                max_length=63,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must contain only letters.", regex="^[a-zA-Z]+$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="callrequest",
            name="name",
            field=models.CharField(
                max_length=63,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must contain only letters.", regex="^[a-zA-Z]+$"
                    )
                ],
            ),
        ),
    ]
