# Generated by Django 4.1 on 2024-01-08 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0009_alter_advice_answer_alter_advice_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="agency.eventtype"
            ),
        ),
    ]
