# Generated by Django 4.1 on 2024-01-08 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0010_alter_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="service",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="agency.service",
            ),
            preserve_default=False,
        ),
    ]
