# Generated by Django 4.1 on 2024-01-08 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0012_alter_callrequest_city_alter_callrequest_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.CharField(
                default=1,
                max_length=63,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Word must contain only letters.", regex="^[a-zA-Z]+$"
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="venue",
            field=models.CharField(default=2, max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                max_length=63,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Word must contain only letters.", regex="^[a-zA-Z]+$"
                    )
                ],
            ),
        ),
    ]
