# Generated by Django 4.1 on 2024-01-09 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0014_alter_callrequest_city_alter_callrequest_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="phone",
            field=models.CharField(
                default=2,
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+380XXXXXXXXX'.",
                        regex="^\\+380\\d{9}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
