# Generated by Django 4.1 on 2024-01-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0015_event_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="organizers",
        ),
    ]
