# Generated by Django 4.1 on 2024-01-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0016_remove_event_organizers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="name",
        ),
    ]
