# Generated by Django 4.1 on 2024-01-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0017_remove_event_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="advice",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Very High"),
                    (5, "Critical"),
                ],
                default=1,
            ),
        ),
    ]
