# Generated by Django 4.1 on 2024-01-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0020_portfolio"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("done", "done"),
                    ("in_progress", "in_progress"),
                    ("rejected", "rejected"),
                ],
                default="created",
                max_length=64,
            ),
        ),
    ]
