# Generated by Django 4.1 on 2024-01-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0021_event_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advice",
            options={"ordering": ["-priority", "question"]},
        ),
    ]
