# Generated by Django 4.1 on 2024-01-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0022_alter_advice_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["is_approved"]},
        ),
    ]
