# Generated by Django 4.1 on 2024-02-02 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0024_alter_event_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="number_of_guests",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999999),
                ]
            ),
        ),
    ]
