# Generated by Django 4.1 on 2024-02-04 18:45

import agency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0025_alter_event_number_of_guests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizer",
            name="photo",
        ),
        migrations.AddField(
            model_name="service",
            name="presentation",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=agency.models.service_presentation_pdf_file_path,
            ),
        ),
    ]
