# Generated by Django 4.1 on 2024-02-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0028_event_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="callrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("done", "done"),
                    ("in_progress", "in_progress"),
                    ("rejected", "rejected"),
                ],
                default="created",
                max_length=64,
            ),
        ),
    ]
