# Generated by Django 4.1 on 2024-02-12 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0030_alter_callrequest_city_alter_callrequest_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callrequest",
            name="city",
            field=models.CharField(
                blank=True,
                max_length=63,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Word must contain only letters.",
                        regex="^[a-zA-Zа-яА-ЯґҐєЄіІїЇ' ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="callrequest",
            name="name",
            field=models.CharField(
                max_length=63,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Word must contain only letters.",
                        regex="^[a-zA-Zа-яА-ЯґҐєЄіІїЇ' ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="city",
            field=models.CharField(
                max_length=63,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Word must contain only letters.",
                        regex="^[a-zA-Zа-яА-ЯґҐєЄіІїЇ' ]+$",
                    )
                ],
            ),
        ),
    ]
