# Generated by Django 4.1 on 2024-02-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0031_alter_callrequest_city_alter_callrequest_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(max_length=511),
        ),
    ]
