# Generated by Django 4.1 on 2024-02-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0032_alter_service_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date"]},
        ),
    ]
