# Generated by Django 4.1 on 2024-02-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0034_alter_event_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="callrequest",
            options={"ordering": ["-created_at"]},
        ),
    ]
